modLoader = "javafml"
loaderVersion = "[45,)"
#issueTrackerURL = ""
license = "${license}"

[[mods]]
modId = "${modid}"
version = "${version}"
displayName = "${name}"
authors = "${authors}"
description = "${description}"
logoFile = "assets/${modid}/logo.png"

[[dependencies.${modid}]]
modId = "forge"
mandatory = true
versionRange = "[${forge_loader_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modid}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modid}]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_api_version},)"
ordering = "AFTER"
side = "BOTH"
