modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "${license}"

[[mods]]
modId = "${modid}"
version = "${version}"
displayName = "${name}"
authors = "${author}"
description = "${description}"
logoFile = "assets/${modid}/logo.png"

[[dependencies.example]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_loader_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.example]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.example]]
modId = "architectury"
type = "required"
versionRange = "[${architectury_api_version},)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "${modid}.mixins.json"
